# Generated by Django 2.1.3 on 2018-11-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_approved',
            new_name='email_is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
